[functions.send-invite-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-invite-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-invite-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-invite-email/*.html" ]

[functions.save-organization-gcp]
verify_jwt = false

[functions.collection-worker]
verify_jwt = false

[functions.collect-ad-data]
verify_jwt = false

[functions.list-google-customers]
verify_jwt = false

[functions.resolve-access-token]
verify_jwt = false
